---
sidebar: sidebar 
permalink: concepts/licensing.html 
keywords: license, licensing 
summary: Descubra cómo las acciones que puede realizar con Astra Control Center difieren en función del estado de la licencia y cómo afecta el uso que haga de Astra Control Center al consumo de licencias. 
---
= Licencia
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/concepts/


[role="lead"]
Al implementar Astra Control Center, se instala con una licencia de evaluación integrada de 90 días para 4.800 unidades CPU. Si necesita más capacidad o un período de evaluación más largo, o si desea actualizar a una licencia completa, puede obtener una licencia de evaluación diferente o una licencia completa de NetApp.

Usted obtiene una licencia de una de las siguientes maneras:

* Si va a evaluar Astra Control Center y necesita términos de evaluación distintos a los incluidos en la licencia de evaluación integrada, póngase en contacto con NetApp para solicitar un archivo de licencia de evaluación diferente.
* link:https://mysupport.netapp.com/site/["Si ya ha adquirido Astra Control Center, genere su archivo de licencia de NetApp (NLF)"^] Al iniciar sesión en el sitio de soporte de NetApp y navegar a sus licencias de software en el menú Sistemas.


Para obtener más información sobre las licencias necesarias para los back-ends de almacenamiento de ONTAP, consulte link:../get-started/requirements.html["compatibles con los back-ends de almacenamiento"].


NOTE: Asegúrese de que su licencia habilita al menos tantas unidades de CPU como necesite. Si el número de unidades de CPU que gestiona Astra Control Center supera las unidades de CPU disponibles en la nueva licencia que se está aplicando, no podrá aplicar la nueva licencia.



== Licencias de evaluación y licencias completas

Se proporciona una licencia de evaluación integrada con una nueva instalación de Astra Control Center. Una licencia de evaluación habilita las mismas capacidades y funciones que una licencia completa durante un periodo limitado (90 días). Después del período de evaluación, se requiere una licencia completa para continuar con todas las funciones.



== Caducidad de la licencia

Si la licencia de Astra Control Center activa caduca, la funcionalidad de interfaz de usuario y API de las siguientes funciones no están disponibles:

* Snapshots y backups locales manuales
* Snapshot y backups locales programados
* Restauración a partir de una copia de Snapshot o un backup
* Clonado desde una copia de Snapshot o estado actual
* Gestionar nuevas aplicaciones
* Configurar políticas de replicación




== Cómo se calcula el consumo de licencias

Al añadir un nuevo clúster a Astra Control Center, no cuenta con licencias consumidas hasta que Astra Control Center gestione al menos una aplicación que se ejecute en el clúster.

Cuando comienza a administrar una aplicación en un clúster, todas las unidades de CPU de ese clúster se incluyen en el consumo de licencias de Astra Control Center, excepto las unidades de CPU de nodo de clúster Red Hat OpenShift que se notifican mediante un mediante la etiqueta `node-role.kubernetes.io/infra: ""`.


NOTE: Los nodos de infraestructura de Red Hat OpenShift no consumen licencias en Astra Control Center. Para marcar un nodo como un nodo de infraestructura, aplique la etiqueta `node-role.kubernetes.io/infra: ""` al nodo.



== Obtenga más información

* link:../get-started/setup_overview.html#add-a-license-for-astra-control-center["Agregue una licencia cuando configure por primera vez Astra Control Center"]
* link:../use/update-licenses.html["Actualizar una licencia existente"]

