---
sidebar: sidebar 
permalink: use/manage-credentials.html 
keywords: invite users, add users, remove users, delete users 
summary: Añada y elimine credenciales de proveedor de cloud de su cuenta en cualquier momento. Astra utiliza estas credenciales para aprovisionar recursos en su nombre. 
---
= Añada y elimine credenciales
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Añada y elimine credenciales de proveedores de cloud privado local como ONTAP S3, clústeres de Kubernetes gestionados con OpenShift o clústeres de Kubernetes no gestionados de su cuenta en cualquier momento. Astra Control Center utiliza estas credenciales para descubrir los clústeres y las aplicaciones de Kubernetes en los clústeres, y para aprovisionar recursos en su nombre.

Tenga en cuenta que todos los usuarios de Astra Control Center comparten los mismos conjuntos de credenciales.



== Añada credenciales

Puede agregar credenciales a Astra Control Center cuando gestiona los clústeres. Para añadir credenciales al añadir un clúster nuevo, consulte link:../get-started/setup_overview.html#add-cluster["Añada un clúster de Kubernetes"].


IMPORTANT: Si crea el suyo propio `kubeconfig` file, debe definir sólo un elemento de contexto *uno* en él. Consulte https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/["Documentación de Kubernetes"^] para obtener información acerca de cómo crear `kubeconfig` archivos.



== Quite las credenciales

Eliminar credenciales de una cuenta en cualquier momento. Solo debe quitar credenciales después de link:unmanage.html["desgestione todos los clústeres asociados"].


NOTE: El primer conjunto de credenciales que agregue a Astra Control Center está siempre en uso porque Astra Control Center utiliza las credenciales para autenticarse en el bloque de copia de seguridad. Lo mejor es no eliminar estas credenciales.

.Pasos
. Seleccione *cuenta*.
. Seleccione la ficha *credenciales*.
. Seleccione el menú Opciones de la columna *Estado* para obtener las credenciales que desea quitar.
. Seleccione *Quitar*.
. Escriba la palabra "quitar" para confirmar la eliminación y, a continuación, seleccione *Sí, Eliminar credenciales*.


.Resultado
Astra Control Center elimina las credenciales de la cuenta.
