---
sidebar: sidebar 
permalink: use/manage-buckets.html 
keywords: how to set up object storage in astra, how to set up astra buckets, s3, astra, setting up astra control, astra control center, kubernetes 
summary: Añadir proveedores de bloques de almacenamiento de objetos es esencial si desea realizar backups de sus aplicaciones y del almacenamiento persistente o si desea clonar aplicaciones entre clústeres. 
---
= Gestionar bloques
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Un proveedor de bloques de almacenamiento de objetos es esencial si desea realizar backups de las aplicaciones y del almacenamiento persistente o si desea clonar aplicaciones entre clústeres. Con Astra Control Center, agregue un proveedor de almacenes de objetos como destino de copia de seguridad fuera del clúster para sus aplicaciones.

No necesita un bucket si va a clonar su configuración de aplicaciones y almacenamiento persistente en el mismo clúster.

Use uno de los siguientes proveedores de bloques de Amazon simple Storage Service (S3):

* ONTAP S3 de NetApp
* StorageGRID S3 de NetApp
* Microsoft Azure
* Genérico S3
+

NOTE: Amazon Web Services (AWS) y Google Cloud Platform (GCP) utilizan el tipo de bloque Generic S3.

+

NOTE: Aunque Astra Control Center es compatible con Amazon S3 como proveedor de bloques Generic S3, es posible que Astra Control Center no admita todos los proveedores de almacenes de objetos que afirman que Amazon es compatible con S3.



Un cubo puede estar en uno de estos estados:

* Pending: Se ha programado la detección del bloque.
* Disponible: El cucharón está disponible para su uso.
* Eliminado: No se puede acceder al depósito actualmente.


Para obtener instrucciones sobre cómo gestionar los cubos con la API Astra Control, consulte link:https://docs.netapp.com/us-en/astra-automation/["Información sobre API y automatización de Astra"^].

Puede realizar estas tareas relacionadas con la gestión de bloques:

* link:../get-started/setup_overview.html#add-a-bucket["Añadir un bucket"]
* <<Editar un bloque>>
* <<Establecer el bloque predeterminado>>
* <<Gire o elimine las credenciales del cucharón>>
* <<Retirar un cucharón>>



NOTE: Los bloques de S3 de Astra Control Center no informan sobre la capacidad disponible. Antes de realizar una copia de seguridad o clonar aplicaciones gestionadas por Astra Control Center, compruebe la información de los bloques en el sistema de gestión ONTAP o StorageGRID.



== Editar un bloque

Puede cambiar la información de credenciales de acceso de un bloque y cambiar si un bloque seleccionado es el bloque predeterminado.


NOTE: Cuando agregue un bloque, seleccione el proveedor de segmento correcto y proporcione las credenciales correctas para ese proveedor. Por ejemplo, la interfaz de usuario acepta ONTAP S3 de NetApp como tipo y acepta credenciales de StorageGRID; sin embargo, esto hará que se produzcan errores en todos los futuros backups de aplicaciones y restauraciones usando este bucket. Consulte link:../release-notes/known-issues.html#selecting-a-bucket-provider-type-with-credentials-for-another-type-causes-data-protection-failures["Notas de la versión"].

.Pasos
. En la navegación de la izquierda, seleccione *Cuchos*.
. En el menú de la columna *acciones*, seleccione *Editar*.
. Cambie cualquier información que no sea el tipo de segmento.
+

TIP: No puede modificar el tipo de segmento.

. Seleccione *Actualizar*.




== Establecer el bloque predeterminado

Cuando se realiza un clon entre clústeres, Astra Control requiere un bloque predeterminado. Siga estos pasos para establecer un bloque predeterminado para todos los clústeres.

.Pasos
. Vaya a *instancias de cloud*.
. Seleccione el menú en la columna *acciones* para la instancia de nube de la lista.
. Seleccione *Editar*.
. En la lista *bloque*, seleccione el segmento que desea que sea el predeterminado.
. Seleccione *Guardar*.




== Gire o elimine las credenciales del cucharón

Astra Control utiliza las credenciales de bloque para obtener acceso y proporcionar claves secretas para un bloque de S3, de forma que Astra Control Center pueda comunicarse con el cucharón.



=== Rotar las credenciales del cucharón

Si gira las credenciales, gírelos durante una ventana de mantenimiento cuando no haya copias de seguridad en curso (programadas o bajo demanda).

.Pasos para editar y girar credenciales
. En la navegación de la izquierda, seleccione *Cuchos*.
. En el menú Opciones de la columna *acciones*, seleccione *Editar*.
. Cree la nueva credencial.
. Seleccione *Actualizar*.




=== Quitar las credenciales del bloque

Debe eliminar las credenciales de bloque solo si se han aplicado credenciales nuevas a un bloque o si ya no se utiliza el bloque de forma activa.


TIP: El primer conjunto de credenciales que agregue a Astra Control siempre está en uso porque Astra Control utiliza las credenciales para autenticar el bloque de copia de seguridad. No elimine estas credenciales si el bloque está en uso activo, ya que esto dará lugar a fallos de copia de seguridad y a falta de disponibilidad de copia de seguridad.


NOTE: Si elimina las credenciales de bloque activas, consulte https://["solución de problemas de eliminación de credenciales del bloque"].

Para obtener instrucciones sobre cómo eliminar credenciales de S3 mediante la API Astra Control, consulte link:https://docs.netapp.com/us-en/astra-automation/["Información sobre API y automatización de Astra"^].



== Retirar un cucharón

Puede eliminar un cubo que ya no esté en uso o que no esté sano. Se recomienda hacer esto para mantener la configuración del almacén de objetos sencilla y actualizada.


NOTE: No se puede eliminar un bloque predeterminado. Si desea eliminar ese bloque, seleccione primero otro bloque como predeterminado.

.Antes de empezar
* Antes de empezar, debe comprobar que no hay copias de seguridad en ejecución o completadas para este bloque.
* Debe comprobar que el bloque no se esté utilizando en ninguna política de protección activa.


Si lo hay, no podrá continuar.

.Pasos
. En la navegación de la izquierda, seleccione *Cuchos*.
. En el menú *acciones*, seleccione *Quitar*.
+

NOTE: Astra Control garantiza en primer lugar que no existan normativas de programación utilizando el bloque para copias de seguridad y que no haya copias de seguridad activas en el bloque que va a eliminar.

. Escriba "eliminar" para confirmar la acción.
. Seleccione *Sí, retire la cuchara*.




== Obtenga más información

* https://["Utilice la API Astra Control"^]

