---
sidebar: sidebar 
permalink: use/uninstall_acc.html 
keywords: astra, astra control center, uninstall, remove 
summary: Describe cómo retirar Astra Control Center y el operador Astra Control Center. 
---
= Desinstale Astra Control Center
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Es posible que necesite eliminar los componentes de Astra Control Center si va a actualizar de una versión de prueba a una versión completa del producto. Para retirar el Centro de control Astra y el operador del Centro de control Astra, ejecute las instrucciones descritas en este procedimiento en secuencia.

Si tiene algún problema con la desinstalación, consulte <<Solución de problemas de desinstalación>>.

.Antes de empezar
. link:../use/unmanage.html#unmanage-an-app["Anular la gestión de todas las aplicaciones"^] en los clústeres.
. link:../use/unmanage.html#unmanage-a-cluster["Anule la gestión de todos los clústeres"^].


.Pasos
. Eliminar Astra Control Center. El comando de ejemplo siguiente se basa en una instalación predeterminada. Modifique el comando si ha realizado configuraciones personalizadas.
+
[listing]
----
kubectl delete -f astra_control_center.yaml -n netapp-acc
----
+
Resultado:

+
[listing]
----
astracontrolcenter.astra.netapp.io "astra" deleted
----
. Utilice el siguiente comando para eliminar la `netapp-acc` espacio de nombres (o con nombre personalizado):
+
[listing]
----
kubectl delete ns [netapp-acc or custom namespace]
----
+
Resultado de ejemplo:

+
[listing]
----
namespace "netapp-acc" deleted
----
. Utilice el siguiente comando para eliminar los componentes del sistema del operador de Astra Control Center:
+
[listing]
----
kubectl delete -f astra_control_center_operator_deploy.yaml
----
+
Resultado:

+
[listing]
----
namespace/netapp-acc-operator deleted
customresourcedefinition.apiextensions.k8s.io/astracontrolcenters.astra.netapp.io deleted
role.rbac.authorization.k8s.io/acc-operator-leader-election-role deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-manager-role deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-metrics-reader deleted
clusterrole.rbac.authorization.k8s.io/acc-operator-proxy-role deleted
rolebinding.rbac.authorization.k8s.io/acc-operator-leader-election-rolebinding deleted
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-manager-rolebinding deleted
clusterrolebinding.rbac.authorization.k8s.io/acc-operator-proxy-rolebinding deleted
configmap/acc-operator-manager-config deleted
service/acc-operator-controller-manager-metrics-service deleted
deployment.apps/acc-operator-controller-manager deleted
----




== Solución de problemas de desinstalación

Utilice las siguientes soluciones alternativas para solucionar cualquier problema que tenga al desinstalar Astra Control Center.



=== La desinstalación de Astra Control Center no puede limpiar el módulo de control del operador de supervisión en el clúster gestionado

Si no ha desgestionar los clústeres antes de desinstalar Astra Control Center, puede eliminar manualmente los POD del espacio de nombres para la supervisión de netapp y el espacio de nombres con los siguientes comandos:

.Pasos
. Eliminar `acc-monitoring` agente:
+
[listing]
----
kubectl delete agents acc-monitoring -n netapp-monitoring
----
+
Resultado:

+
[listing]
----
agent.monitoring.netapp.com "acc-monitoring" deleted
----
. Elimine el espacio de nombres:
+
[listing]
----
kubectl delete ns netapp-monitoring
----
+
Resultado:

+
[listing]
----
namespace "netapp-monitoring" deleted
----
. Confirme los recursos eliminados:
+
[listing]
----
kubectl get pods -n netapp-monitoring
----
+
Resultado:

+
[listing]
----
No resources found in netapp-monitoring namespace.
----
. Confirme que se ha eliminado el agente de supervisión:
+
[listing]
----
kubectl get crd|grep agent
----
+
Resultado de la muestra:

+
[listing]
----
agents.monitoring.netapp.com                     2021-07-21T06:08:13Z
----
. Eliminar información de definición de recursos personalizada (CRD):
+
[listing]
----
kubectl delete crds agents.monitoring.netapp.com
----
+
Resultado:

+
[listing]
----
customresourcedefinition.apiextensions.k8s.io "agents.monitoring.netapp.com" deleted
----




=== La desinstalación de Astra Control Center no limpia los CRD de Traefik

Puede eliminar manualmente los CRD de Traefik. Los CRD son recursos globales y su eliminación podría afectar a otras aplicaciones del cluster.

.Pasos
. Enumere los CRD de Traefik instalados en el clúster:
+
[listing]
----
kubectl get crds |grep -E 'traefik'
----
+
Respuesta

+
[listing]
----
ingressroutes.traefik.containo.us             2021-06-23T23:29:11Z
ingressroutetcps.traefik.containo.us          2021-06-23T23:29:11Z
ingressrouteudps.traefik.containo.us          2021-06-23T23:29:12Z
middlewares.traefik.containo.us               2021-06-23T23:29:12Z
middlewaretcps.traefik.containo.us            2021-06-23T23:29:12Z
serverstransports.traefik.containo.us         2021-06-23T23:29:13Z
tlsoptions.traefik.containo.us                2021-06-23T23:29:13Z
tlsstores.traefik.containo.us                 2021-06-23T23:29:14Z
traefikservices.traefik.containo.us           2021-06-23T23:29:15Z
----
. Eliminar CRD:
+
[listing]
----
kubectl delete crd ingressroutes.traefik.containo.us ingressroutetcps.traefik.containo.us ingressrouteudps.traefik.containo.us middlewares.traefik.containo.us serverstransports.traefik.containo.us tlsoptions.traefik.containo.us tlsstores.traefik.containo.us traefikservices.traefik.containo.us middlewaretcps.traefik.containo.us
----




== Obtenga más información

* link:../release-notes/known-issues.html["Problemas conocidos para la desinstalación"]

