---
sidebar: sidebar 
permalink: use/update-licenses.html 
keywords: manage, licenses, licensing, Astra Control Center, add license, update license 
summary: Puede convertir una licencia de evaluación a una licencia completa, o puede actualizar una evaluación existente o una licencia completa con una nueva licencia. 
---
= Actualizar una licencia existente
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Puede convertir una licencia de evaluación a una licencia completa, o puede actualizar una evaluación existente o una licencia completa con una nueva licencia. Si no tiene una licencia completa, trabaje con su contacto de ventas de NetApp para obtener un número de serie y una licencia completa. Puede utilizar la interfaz de usuario de Astra Control Center o https://docs.netapp.com/us-en/astra-automation/index.html["La API de control Astra"^] para actualizar una licencia existente.

.Pasos
. Inicie sesión en la https://mysupport.netapp.com/site/["Sitio de soporte de NetApp"^].
. Acceda a la página de descarga de Astra Control Center, introduzca el número de serie y descargue el archivo de licencia completo de NetApp (NLF).
. Inicie sesión en la interfaz de usuario de Astra Control Center.
. En la navegación de la izquierda, seleccione *cuenta* > *Licencia*.
. En la página *cuenta* > *Licencia*, seleccione el menú desplegable de estado de la licencia existente y seleccione *Reemplazar*.
. Busque el archivo de licencia que descargó.
. Seleccione *Agregar*.


La página *cuenta* > *licencias* muestra la información de la licencia, la fecha de caducidad, el número de serie de la licencia, el ID de cuenta y las unidades de CPU utilizadas.



== Si quiere más información

* link:../concepts/licensing.html["Licencias de Astra Control Center"]

