---
sidebar: sidebar 
permalink: use/view-clusters.html 
keywords: view cluster, edit storage class, storage class, cluster storage, cluster overview 
summary: Después de añadir clústeres a Astra Control Center, puede ver detalles sobre el clúster, como su ubicación, los nodos de trabajo, los volúmenes persistentes y las clases de almacenamiento. También puede cambiar las clases de almacenamiento predeterminadas. 
---
= Consulte el estado del clúster y gestione las clases de almacenamiento
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Después de añadir clústeres que debe gestionar Astra Control Center, puede ver detalles sobre el clúster, como su ubicación, los nodos de trabajo, los volúmenes persistentes y las clases de almacenamiento. También es posible cambiar la clase de almacenamiento predeterminada para los clústeres gestionados.



== Ver el estado y los detalles del clúster

Puede ver detalles sobre el clúster, como la ubicación, los nodos de trabajo, los volúmenes persistentes y las clases de almacenamiento.

.Pasos
. En la interfaz de usuario de Astra Control Center, seleccione *Clusters*.
. En la página *Clusters*, seleccione el clúster cuyos detalles desea ver.
+

NOTE: Si hay un clúster en `removed` estado aunque la conectividad del clúster y de la red parece correcta (los intentos externos de acceder al clúster mediante las API de Kubernetes se han realizado correctamente), es posible que la imagen que proporcionó a Astra Control ya no sea válida. Esto puede deberse a la rotación o a la caducidad del certificado en el clúster. Para corregir este problema, actualice las credenciales asociadas con el clúster en Astra Control mediante link:https://docs.netapp.com/us-en/astra-automation/index.html["API de control Astra"].

. Consulte la información en las pestañas *Descripción general*, *almacenamiento* y *actividad* para encontrar la información que busca.
+
** *Descripción general*: Detalles sobre los nodos de trabajo, incluido su estado.
** *almacenamiento*: Los volúmenes persistentes asociados con el cálculo, incluyendo la clase de almacenamiento y el estado.
** *Actividad*: Muestra las actividades relacionadas con el cluster.





NOTE: También puede ver la información del clúster a partir de Astra Control Center *Dashboard*. En la ficha *Clusters* de *Resumen de recursos*, puede seleccionar los clústeres administrados, que le llevará a la página *Clusters*. Después de llegar a la página *Clusters*, siga los pasos descritos anteriormente.



== Cambie la clase de almacenamiento predeterminada

Es posible cambiar la clase de almacenamiento predeterminada para un clúster de. Cuando Astra Control gestiona un clúster, realiza un seguimiento de la clase de almacenamiento predeterminada del clúster.


NOTE: No cambie la clase de almacenamiento con comandos kubectl. Utilice este procedimiento en su lugar. Astra Control revertirá los cambios si se realizan con kubectl.

.Pasos
. En la interfaz de usuario web de Astra Control Center, seleccione *Clusters*.
. En la página *Clusters*, seleccione el clúster que desea cambiar.
. Seleccione la ficha *almacenamiento*.
. Seleccione la categoría *clases de almacenamiento*.
. Seleccione el menú *acciones* para la clase de almacenamiento que desea establecer como predeterminada.
. Seleccione *establecer como predeterminado*.

