---
sidebar: sidebar 
permalink: get-started/add-storage-backend.html 
keywords: set up astra control, astra control license, add cluster, add storage backend, import storage, add bucket 
summary: Después de habilitar la autenticación del back-end de almacenamiento, debe seleccionar un back-end de almacenamiento para gestionarlo. 
---
= Añada un back-end de almacenamiento
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Después de configurar las credenciales o la información de autenticación de certificados, puede añadir un back-end de almacenamiento de ONTAP existente a Astra Control Center para gestionar sus recursos.

Gestionar los clústeres de almacenamiento en Astra Control como back-end de almacenamiento le permite obtener vínculos entre los volúmenes persistentes (VP) y el back-end de almacenamiento, así como mediciones de almacenamiento adicionales.

Añadir y gestionar back-ends de almacenamiento de ONTAP en Astra Control Center es opcional cuando se utiliza la tecnología SnapMirror de NetApp si has habilitado el aprovisionador de control de Astra.

.Pasos
. En el panel de control del área de navegación de la izquierda, seleccione *Backends*.
. Seleccione *Agregar*.
. En la sección Usar existente de la página Agregar backend de almacenamiento, seleccione *ONTAP*.
. Seleccione una de las siguientes opciones:
+
** *Usar credenciales de administrador*: Ingrese la dirección IP de administración del clúster de ONTAP y las credenciales de administración. Las credenciales deben ser credenciales para todo el clúster.
+

NOTE: El usuario cuyas credenciales introduzca aquí debe tener la `ontapi` Método de acceso de inicio de sesión de usuario habilitado en System Manager de ONTAP en el clúster de ONTAP. Si planea utilizar la replicación de SnapMirror, aplique las credenciales de usuario con el rol "admin", que tiene los métodos de acceso `ontapi` y.. `http`, En clústeres ONTAP de origen y destino. Consulte https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/concept_cluster_user_accounts.html#users-list["Gestionar cuentas de usuario en la documentación de ONTAP"^] si quiere más información.

** *Utilice un certificado*: Cargue el certificado `.pem` archivo, la clave de certificado `.key` archivo y, opcionalmente, el archivo de entidad de certificación.


. Seleccione *Siguiente*.
. Confirme los detalles del backend y seleccione *Administrar*.


.Resultado
El back-end aparece en la `online` estado en la lista con información resumida.


NOTE: Es posible que deba actualizar la página para que se muestre el back-end.
